allowBuilds:
  esbuild: false
  unrs-resolver: false
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@hono/node-server@2.0.5'
overrides:
  '@hono/node-server@<2.0.5': ^2.0.5
publicHoistPattern:
  - '*prettier*'
